### PR TITLE
Bubbles disposition

### PR DESCRIPTION
**Pull request by tomriiich**

### CODE REVIEW

**Comment by rocambille** [comment]
conflicts to resolve

**Comment by tomriiich** [comment]
Yes I've seen that but I can't access to the "resolve conflicts" button...

**Comment by rocambille** [comment]
> Yes I've seen that but I can't access to the "resolve conflicts" button...

then do it locally on your computer ;)

**Comment by tomriiich** [comment]
I tried to do this but there are no problems locally on my computer

**Pull request merged**
